name: Merge
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - 'main'
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get last commit SHA
        id: get_sha
        run: |
          echo "sha=${{ github.event.before }}" >> $GITHUB_OUTPUT
      - name: Search branch by name
        id: get_branch_id
        run: |
          branch_id=$(curl --silent \
            "https://console.neon.tech/api/v2/projects/${PROJECT_ID}/branches" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${API_KEY}" \
            | jq -r .branches \
            | jq -c '.[] | select(.name | contains("'${SHA}'")) .id' \
            | jq -r \
            ) \
            
          echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT
        env:
          PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
          API_KEY: ${{ secrets.NEON_API_KEY }}
          SHA: ${{ steps.get_sha.outputs.sha }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env
          echo SHADOW_DATABASE_URL=${{secrets.SHADOW_DATABASE_URL}} >> .env
          npx prisma migrate dev

      - name: Deploy to Vercel
        id: deploy
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=${preview_url}" >> $GITHUB_OUTPUT

      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_id: ${{ steps.get_branch_id.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}
